name: Build Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            id: win

          - name: macOS
            os: macos-latest
            id: mac
            args: '"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64"'

          - name: Linux
            os: ubuntu-latest
            id: linux

          - name: Android (32-bit)
            os: ubuntu-latest
            id: android32
            args: '-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23'

          - name: Android (64-bit)
            os: ubuntu-latest
            id: android64
            args: '-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23'

          - name: iOS
            os: macos-latest
            id: ios
            args: '-DCMAKE_SYSTEM_NAME=iOS'

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CPM Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/cpm-cache
          key: cpm-${{ matrix.config.id }}-v1-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            cpm-${{ matrix.config.id }}-v1-

      - name: Configure and Build
        shell: bash
        run: |
          export CPM_SOURCE_CACHE=${{ github.workspace }}/cpm-cache
          mkdir build
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ${{ matrix.config.args }}
          cmake --build build --config Release
