name: Build Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        config:
          - name: Windows
            os: windows-latest

          - name: macOS
            os: macos-latest
            args: '"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64"'

          - name: Linux
            os: ubuntu-latest

          - name: Android (32-bit)
            os: ubuntu-latest
            args: '-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23'

          - name: Android (64-bit)
            os: ubuntu-latest
            args: '-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23'

          - name: iOS
            os: macos-latest
            args: '-DCMAKE_SYSTEM_NAME=iOS'

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir build
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ${{ matrix.config.args }}

      - name: Build
        run: |
          cd build
          cmake --build build --config Release
